# Generated by Django 4.2.4 on 2024-06-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
