# Generated by Django 4.2.4 on 2024-06-23 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+\\d{1,3}\\d{6,14}$'), django.core.validators.MinLengthValidator(7)]),
        ),
    ]
